# Generated by Django 2.2.12 on 2020-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('attachment', models.FileField(error_messages={'required': 'Attach client approved time sheet)'}, upload_to='media/attachment/')),
            ],
        ),
    ]
