# Generated by Django 2.2.12 on 2020-08-04 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_auto_20200804_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
