# Generated by Django 2.2.12 on 2020-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20200804_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='attachment',
            field=models.FileField(error_messages={'required': 'Please enter your name'}, upload_to='media/attachment/'),
        ),
    ]
