# Generated by Django 2.2.12 on 2020-08-05 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20200804_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time',
            field=models.PositiveIntegerField(default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
