# Generated by Django 2.2.12 on 2020-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20200805_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='attachment',
            field=models.FileField(upload_to='media/attachment/'),
        ),
    ]
